workflows: 
  ace-release: 
    name: Ace release
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Build
        script: |
          sudo npm install --save-dev webpack webpack-cli
          cd www && mkdir dist && cd ..
          npm run build
      - name: install cordova
        script: |
          ls
          sudo npm install -g cordova@6.0.0
      - name: add android project
        script: |
          sudo cordova platform add android
          sh clean.sh
          cd platforms
          sudo cordova build android
          ls -a
          pwd
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk


