workflows: 
  ace-release: 
    name: Ace release
    environment:
      java: 1.8
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Build
        script: |
          sudo pkg install node
          sudo npm install --save-dev webpack webpack-cli
          cd www && mkdir dist && cd ..
          npm run build
          ls
          sudo npm install -g cordova@11.0.0
          sudo cordova platform add android
          sh clean.sh
          cd platforms
          sudo cordova build android
          ls -a
          pwd
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk


