version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.01.1-node
    steps:
      - checkout
      - run:
         name: generate android project
         command: |
           npm install --save-dev webpack webpack-cli
           cd www && mkdir dist && cd ..
           npm run build
           ls
           npm install -g cordova@11.0.0
           cordova platform add android
           ls
           cordova plugin add cordova-plugin-file@7.0.0
           sh clean.sh
           cd platforms
           export ANDROID_HOME=/home/circleci/android-sdk
           export ANDROID_SDK_ROOT=/home/circleci/android-sdk
           export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
           export PATH=$PATH:/home/circleci/android-sdk:/
           cordova build android
           ls -a
           ls -lh android/app/build/outputs/apk/debug/

      - store_artifacts:
          path: android/app/build/outputs/apk/debug/app-debug.apk

