version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.01.1
    steps:
      - checkout
      - run:
         name: generate android project
         command: |
           sudo npm install --save-dev webpack webpack-cli
           cd www && mkdir dist && cd ..
           npm run build
           ls
           sudo npm install -g cordova@11.0.0
           sudo cordova platform add android
           ls
           sudo cordova plugin add cordova-plugin-file
           sh clean.sh
           cd platforms
           sudo cordova build android
           ls -a
           ls -lh android/app/build/outputs/apk/debug/

      - store_artifacts:
          path: android/app/build/outputs/apk/debug/app-debug.apk

