name: Build app

on:
  push:
    branches:
      - master

jobs:
  build-Ace-Code:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: 16
     - run: sudo npm install --save-dev webpack webpack-cli
     - run: cd www && mkdir dist && cd ..
     - run: npm run build
     - run: sudo rm -rf /usr/local/lib/android/sdk/cmdline-tools/latest/
     - run: sudo npm install -g cordova@11.0.0
     - run: sudo cordova platform add android
     - run: ls
     - run: |
         sudo cordova plugin add cordova-plugin-file
         sudo cordova plugin add cordova-plugin-background-mode-fixed

     - uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: 17

     - uses: gradle/actions/setup-gradle@v4
       with:
         gradle-version: "7.4.2"
     - name: Setup sdk
       uses: android-actions/setup-android@v3
       with:
         cmdline-tools-version: 12266719
  

     - run: sh clean.sh
     - run: |
         export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
         export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools/
         export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
         export PATH=$PATH:$ANDROID_SDK_ROOT/emulator/
         gh release create ${{ github.run_number }} /home/runner/work/Ace-Code/Ace-Code/platforms/android/CordovaLib/cordova.gradle
         cd /home/runner/work/Ace-Code/Ace-Code/platforms/android/
         sudo gradle wrapper --gradle-version 8.0
         cd -
         sudo apt-get install zipalign
         cd platforms
         sudo cordova build android
         ls -a
         ls -lh android/app/build/outputs/apk/debug/
         cd android/app/build/outputs/apk/debug/
         sudo mv app-debug.apk /home/runner/work/Ace-Code/Ace-Code/
         cd /home/runner/work/Ace-Code/Ace-Code
       env:
         GITHUB_TOKEN: ${{ secrets.TK }}


     - name: upload Release Apk
       run: |
         gh release create ${{ github.run_number }} /home/runner/work/Ace-Code/Ace-Code/app-debug.apk
       env:
         GITHUB_TOKEN: ${{ secrets.TK }}
