name: Build app

on:
  push:
    branches: master

jobs:
  build-Ace-Code:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 16
     
     - run: sudo npm install -g cordova
     - run: ls
     - run: cordova platform add android

     - uses: actions/setup-java@v3
       with:
         distribution: temurin
         java-version: 11
     
     - uses: gradle/gradle-build-action@v2
     - name: Setup sdk
       uses: android-actions/setup-android@v2

     - run: |
         cd platforms
         cordova build android
         ls -a
         ls android/app/build/outputs/apk/debug/
     - run: pwd

     - uses: actions/upload-artifact@v3
       with:
         name: upload_debug
         path: /home/runner/work/Ace-Code/Ace-Code/platforms/a    ndroid/app/build/outputs/apk/debug/debug-apk.apk
     
     - uses: actions/download-artifact@v3 
       with:
         name: Upload_debug

     - run: ls
     
